### ISSUE TITLE
options and info gone

### ISSUE THREAD

**Issue by dylanjtholen** [R5-3600/cookie_clicker-steam#1]
there is no 'options' or 'info' buttons

**Comment by wednesday2024** [comment]
> there is no 'options' or 'info' buttons

That is weird. I just noticed that. Thanks for letting me know. I will look into this.

**Comment by wednesday2024** [comment]
> there is no 'options' or 'info' buttons

I just found the issue. Again, thanks for bringing this to my attention. The fix will be out in a minute.
